---
title: "Cohort 1"
author: "Abhijit Dasgupta"
output: html_document
---

## Notebooks

```{r, echo=F}
d <- data.frame('Day' = 1, 'Notebook' = '[link](Lectures/Cohort1/Day 1 Cohort 1.ipynb)',
                'HTML' = '[link](Lectures/Cohort1/Day 1 Cohort 1.html)',
                'Python' = '[link](Lectures/Cohort1/Day 1 Cohort 1.py)')
d <- rbind(d, data.frame('Day' = 2,
                         'Notebook' = '[link](Lectures/Cohort1/Day2Cohort1.ipynb)',
                         'HTML'='',
                         'Python'=''))
knitr::kable(d)
```

## Python script files

1. Decision Tree from scratch ([link](scripts/MyDT.py))
2. Decision Tree fit and validation ([link](scripts/DTImplementation.py))
3. Introduction to Random Forests ([link](scripts/RFIntro.py))
4. Random Forests deconstructed ([link](scripts/RFDeconstructed.py))
5. Random Forest Tuning ([link](scripts/RFTuning.py))
6. Random Forest metrics and calibration ([link](scripts/RFClassReg.py))
8. Boosting ([link](scripts/boosting.py)) ([In-class code](scripts/Cohort1Day6.py))
9. XGBoost ([link](scripts/xgboost.py))
7. Stacking ([link](scripts/stacking2.py))
10. Pipelines ([link](scripts/pipelines2.py))
11. PMML ([link](scripts/pmml.py))
12. Effect sizes ([link](scripts/effects.py))


## Presentations

1. Introduction to Machine Learning ([link](present/Session1B.pdf))
2. Decision Trees ([link](present/DTSlides.html)) ([pdf](present/DTSlides.pdf))
3. Bias, Variance and Random Forests ([link](present/BiasVariance.html)) ([pdf](present/BiasVariance.pdf))
4. Fitting Random Forests ([link](present/RFFit.html)) ([pdf](present/RFFit.pdf))
5. Boosting ([link](present/boost.html)) ([pdf](present/boost.pdf))
6. Stacking ([link](present/stacking.html))([pdf](present/stacking.pdf))
7. Interpretations ([link](http://webbedfeet.github.io/Dartmouth2)) ([pdf](present/Interpretations.pdf))



# Resources

1. `rpy2` package for calling R from Python. [Windows binaries](http://www.lfd.uci.edu/~gohlke/pythonlibs/#rpy2)

