---
title: "Cohort 2"
author: "Abhijit Dasgupta"
output: html_document
---

[Back to Cohorts page](../cohorts.html)

## Notebooks

```{r, echo=F}
d <- data.frame('Day' = 1, 'Notebook' = '[link](../Lectures/Cohort2/Day 1 Cohort 2.ipynb)',
                'HTML' = '[link](../Lectures/Cohort2/Day 1 Cohort 2.html)',
                'Python' = '[link](../Lectures/Cohort2/Day 1 Cohort 2.py)')
d <- rbind(d, data.frame('Day'=2,
                         'Notebook' = '[link](../Lectures/Cohort2/Day2Cohort2.ipynb)',
                         'HTML'='',
                         'Python'=''))
knitr::kable(d)
```

## Python script files

1. Decision Tree from scratch ([link](../scripts/MyDT.py))
2. Decision Tree fit and validation ([link](../scripts/DTImplementation.py))
3. Introduction to Random Forests ([link](../scripts/RFIntro.py))
4. Random Forests deconstructed ([link](../scripts/RFDeconstructed.py))
5. Random Forest Tuning ([link](../scripts/RFTuning.py))
6. Random Forest metrics and calibration ([link](../scripts/RFClassReg.py))
8. Boosting ([link](../scripts/boosting.py)) ([In-class code](../scripts/Cohort1Day6.py))
9. XGBoost ([link](../scripts/xgboost.py)) ([In class script file](../scripts/Cohort2Day7.py))
7. Stacking ([link](../scripts/stacking2.py))
10. Pipelines ([link](../scripts/pipelines2.py))
11. PMML ([link](../scripts/pmml.py))
12. Effect sizes ([link](../scripts/effects.py))


## ../../presentations

1. Introduction to Machine Learning ([link](../present/Session1B.pdf))
2. Decision Trees ([link](../present/DTSlides.html)) ([pdf](../present/DTSlides.pdf))
3. Bias, Variance and Random Forests ([link](../present/BiasVariance.html)) ([pdf](../present/BiasVariance.pdf))
4. Fitting Random Forests ([link](../present/RFFit.html)) ([pdf](../present/RFFit.pdf))
5. Boosting ([link](../present/boost.html)) ([pdf](../present/boost.pdf))
6. Stacking ([link](../present/stacking.html))([pdf](../present/stacking.pdf))
7. Interpretations ([link](http://webbedfeet.github.io/Dartmouth2)) ([pdf](../present/Interpretations.pdf))



# Resources

1. `rpy2` package for calling R from Python. [Windows binaries](http://www.lfd.uci.edu/~gohlke/pythonlibs/#rpy2)

