---
title: "Cohort 4"
author: "Abhijit Dasgupta"
date: "October 2, 2017"
output: html_document
---

[Back to Cohorts page](../cohorts.html)

## Presentations

1. Introduction (<a href = "../present/Introduction.html" target="_blank">link</a>)
2. Introduction to Machine Learning ([link](../present/IntroToML.pdf))
3. Introduction to Decision Trees (<a href="../present/DTSlides.html" target="_blank">link</a>)
4. Unbalanced data (<a href='../present/Unbalanced.html' target = '_blank'>link</a>)
5. The Bias-Variance Tradeoff (<a href = "../present/BiasVariance.html" target = "_blank">link</a>)
6. Fitting Random Forests (<a href = "../present/RFFit.html" target="_blank">link</a>)
7. Boosting (<a href = "../present/boost.html" target="_blank">link</a>)
8. XGBoost (<a href="../present/xgboost.html" target="_blank">link</a>)
7. Stacking (<a href="../present/stacking.html" target = "_blank">link</a>)
8. Effect sizes and interpretability (<a href="http://webbedfeet.github.io/Dartmouth2" target='_blank'>link</a>)

## Python Scripts

1. Introduction ([link](../scripts/Introduction.py))([In class](cohort4day1.py))
2. Developing Decision Trees ([link](../scripts/MyDT.py))
2. Decision Tree fit and validation ([link](../scripts/DTImplementation.py))([Day 2 and 3 script](cohort4day2.py))
4. Looking at unbalanced data ([link](../scripts/unbalanced.py))
5. Building bagged trees ([link](../scripts/RFIntro.py))([Day 4 script](cohort4day4.py))
6. Deconstructing a Random Forest ([link](../scripts/RFDeconstructed.py))
7. Tuning a Random Forest ([link](../scripts/RFTuning.py))
8. Fitting a Random Forest ([link](../scripts/RFClassReg.py))([In-class script](cohort4day5.py))
9. Boosting from scratch ([link](../scripts/boosting.py))([In-class script](cohort4day6.py))
10. XGBoost ([link](../scripts/xgboost.py))
8. Stacking ([link](../scripts/stacking.py))
11. A data example ([link](../scripts/examples.py))


## Resources

1. Matplotlib gallery (<a href = "https://matplotlib.org/gallery.html" target = "_blank">link</a>)
2. Examples of decision surfaces of different machine learning methods (<a href="http://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html" target="_blank">link</a>)
3. Scikit-learn documentation (<a href = "http://scikit-learn.org" target="_blank">link</a>)

[Back to Cohorts page](../cohorts.html)